11_I18n/djregistration/app_blog/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path(
        'blogs/',
        BlogsListView.as_view(),
        name='page_blog_index'
    ),
    path(
        'blogs/add/',
        BlogAddView.as_view(),
        name='page_blog_add'
    ),
    path(
        'blogs/import/',
        BlogImportView.as_view(),
        name='page_blog_import'
    ),
    path(
        'blogs/<int:pk>',
        BlogDetailView.as_view(),
        name='page_blog_detail'
    ),
    path(
        'myblog/',
        BlogMyListView.as_view(),
        name='page_my_blog'
    ),
]

11_I18n/djregistration/djregistration/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_news.urls')),
    path('', include('app_users.urls')),
    path('', include('app_blog.urls')),
    path('i18n', include('django.conf.urls.i18n'))
]

11_I18n/djregistration/app_blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _


class Blog(models.Model):
    """
    Список блогов
    """
    user = models.ForeignKey(
        User,
        related_name='blog',
        verbose_name=_('tid_models_blog_user'),  # 'Создатель блога DJDB'
        on_delete=models.CASCADE
    )
    header = models.CharField(
        max_length=200,
        verbose_name=_('tid_label_header'),  # 'Заголовок'
    )
    content = models.TextField(
        verbose_name=_('tid_models_blog_text'),  # 'Текст',
        max_length=5000
    )
    create_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('tid_blog_label_created_at'),  # 'Дата создания'
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('tid_blog_label_updated_at'),  # 'Дата обновления'
    )
    
    def __str__(self):
        return f'{self.header}'
    
    class Meta:
        verbose_name = _('tid_models_blog_meta_vn')  # 'блог'
        verbose_name_plural = _('tid_models_blog_meta_vnp')  # 'блоги'
        db_table = 'blogs'
        ordering = ['-create_at']


class BlogImages(models.Model):
    """
    Изображения для блога
    """
    blog = models.ForeignKey(
        Blog,
        related_name='blog_photos',
        on_delete=models.CASCADE,
        verbose_name=_('tid_models_blog_meta_vn'),  # 'Блог'
    )
    image = models.ImageField(
        verbose_name=_('tid_label_images'),  # 'Изображение',
        upload_to='images/blogs/',
        null=True,
        blank=True
    )
    upload_at = models.DateTimeField(
        verbose_name=_('tid_models_blog_images_upload_at'),  # 'Дата загрузки',
        auto_now_add=True
    )
    
    class Meta:
        verbose_name = _('tid_models_blog_images_meta_vn')  # 'фотка блога'
        verbose_name_plural = _('tid_models_blog_images_meta_vnp')  # 'фотки блога'
        db_table = 'blog_images'
        ordering = ['blog', '-upload_at']

11_I18n/djregistration/templates/pages/blog/myblog/myblog.html
{% extends 'base_template/base_template.html' %}
{% load i18n %}
{% load static %}
{% block content %}
    {% if request.user.is_authenticated %}
        {% include 'auth_template/buttons/blog_buttons.html' %}
    {% else %}
        {% include 'utls_template/alert.html' with bt_theme="warning" bt_text="Чтобы добавить блог, нужно авторизоваться" %}
    {% endif %}
    {% if blog_list %}
        {% for blog_item in blog_list %}
            <b>{% trans "tid_label_header" %}:</b> {{ blog_item.header }}<br><br>
            <b>{% trans "tid_label_content" %}:</b> {{ blog_item.content }}<br><br>
            <b>{% trans "tid_label_images" %} ({{ blog_item.blog_photos.all|length }}):</b>
            <div class="row">
                {% if blog_item.blog_photos.all|length %}
                    {% for image in blog_item.blog_photos.all %}
                        <div class="d-inline">
                            <img class="blog-image" src="{% get_media_prefix %}{{ image.image }}" alt="image #{{ image.id }} of blog #{{ blog_item.id }} by {{ blog_item.user.username }}" height="250">
                        </div>
                    {% endfor %}
                {% else %}
                    {% trans "tid_messages_blog_no_images" as message_blog_no_images %}
                    {% include 'utls_template/alert.html' with bt_theme="info" bt_text=message_blog_no_images %}
                {% endif %}
            </div><br><br>
            <b>{% trans "tid_blog_label_created_at" %}:</b> {{ blog_item.create_at|date:"d.m.Y H:i:s" }}
            <b>{% trans "tid_blog_label_updated_at" %}:</b> {{ blog_item.updated_at|date:"d.m.Y H:i:s" }}
            <hr>
        {% endfor %}
    {% else %}
        {% trans "tid_messages_blog_noone" as message_blog_noone %}
        {% include 'utls_template/alert.html' with bt_theme="info" bt_text=message_blog_noone %}
    {% endif %}
{% endblock %}